### ISSUE TITLE
Des documentations

### ISSUE THREAD

**Issue by imadismail** [jplot/Qodvwr-42#2]
Salut, 
Je viens de découvrir les exercices, tp et projets que vous avez réalisé. Mais vous n'avez pas de cours, de documentation sur le shell, le c, les structures de données, .... etc ??

Je trouves que le contenu est riche et pratique pour former des programmeurs.

**Comment by icrotz** [comment]
https://www.youtube.com/watch?v=J75o9LbiGgg&index=6&list=PLIXVN1KHt2a7UuyDroq9QLJm0sMGfgDj8 regarde cette playlist

**Comment by jplot** [comment]
Tu as tous les PDF [https://github.com/jplot/Piscine_C-42/tree/master/pdf](https://github.com/jplot/Piscine_C-42/tree/master/pdf)

**Comment by jplot** [comment]
Tu as tous les PDF https://github.com/jplot/Piscine_C-42/tree/master/pdf
